### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by cindyming** [YunYinORG/YYF#17]
框架目前并不支持auth 验证 之后会支持吗？

**Comment by NewFuture** [comment]
@cindyming 所言 `auth` 验证指的是 [HTTP Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) 吗?

**Comment by NewFuture** [comment]
验证的话,,目前来看写在框架里不太合适,

可以扩展[REST](https://github.com/YunYinORG/YYF/blob/master/library/Rest.php)
添加一个 init方法,加入自己的验证逻辑
如下
```php
class AuthRest extends Rest{
  
  protected function init(){
      parent::init();//完成REST初始化，顺序可调
      $this->auth();//调用验证逻辑
  }
  
  public function auth(){
    //完成验证逻辑
  }
}
```

参考文档 https://yyf.newfuture.cc/controller/rest.html
