### ISSUE TITLE
RESTful有个对版本控制的东西

### ISSUE THREAD

**Issue by m9rco** [YunYinORG/YYF#20]
记得`RESTful`有个`Versioning `的东西 ，楼主大大您是如何实现的呢

**Comment by NewFuture** [comment]
## 接口调用方式

RESTful API的多版本调用方式常见两种

* 在URL中`https://base.url/[Version]/resource/address?query`,也有放在后缀或者query里面的
* 在HTTP header中如`Version:[version]`

为Web提供服务的API常用的是放在`URL`中，因为这样 **兼容性** 和 **便捷性** 更高

------------
## 实现方案

一般不同版本的API是分批次开发的(不是同时开始的)，代码共存和不共存都可能存在。

三种实现方案：
* 【机器层】多机部署+反向代理: 每个机器独立运行不同版本的API，反向代理根据版本来源，转发到对应版本的服务器。
    * 优点: 灵活度高，版本之间无干扰
    * 缺点: 成本高，维护配置复杂
* 【服务层】单机部署URL重写: 由Apache等HTTPServer层来做,根据不同版本请求，调用对应入口
    * 优点: 配置相对简单
    * 缺点: 依赖于服务器，依赖代码实现，匹配模式固定
*  【代码层】不同版本使用不同代码: 可以是`多入口`或者`多模块`
    * 优点: 完全由代码定义,不依赖于服务器
    * 缺点: 灵活度有限

第一种方案时候大规模集群且版本之间无依赖(各版本可能是独立维护)，

规模不大或者代码相互依赖通常可用后两种方案

**Comment by m9rco** [comment]
若是代码层，我只能有一个入口，以`YYF`或者`Yaf`是做不到的把，照我的理解`Yaf`最多路由三层

**Comment by NewFuture** [comment]
如果从代码层实现:

#### 1. 多入口方案
每个版本使用不同的入口

`https://base.url/api.v1.0.php/resource/address?query`
`https://base.url/api.v2.0.php/resource/address?query`

默认只有一个入口 [index.php](https://github.com/YunYinORG/YYF/blob/master/public/index.php)
可以添加新的入口如 `api.v1.0.php`  `api.v2.0.php` 

这种方式不同入口可以调用不同配置和指定不同项目入口，但是比较丑陋，可配合重写美化

#### 2. 多模块方案
YAF 本身是支持多模块的，YYF 这里可以开启多模块支持  https://github.com/YunYinORG/YYF/blob/master/conf/app.ini#L6

可以根据建立如 `v1`,`v2`这些模块(目录)
`https://base.url/v1/resource/address`  会自动映射到 v1模块

**Comment by m9rco** [comment]
硬性要求我只能拥有一个入口 只能有一个`index.php` ，我指的是web服务器只允许映射到一个目录，我指的最多三层是表示`/m/c/a` ,由于`Route_Interface`最终只能转为`m=&c=&a=`但我目前需要但是`/m/v/c/a` ，虽然看起来好像很简单能实现但样子，但真正去实践后发现并不如人意，看来只能自己写个精简的`RESTful`框架了。。楼主有好的推荐吗

**Comment by NewFuture** [comment]
最简单的方式使用多模块 
1. 配置
  ```ini
   application.modules = "v1,v2"; 开启的模块
   application.dispatcher.defaultAction = "v2" ;默认模块(不带版本号)
  ```
2. 然后建两个文件夹
`https://base.url/resource/address` => `app/`下的代码
`https://base.url/v1/resource/address` => `app/modules/V1/` v1的代码（和 `app`下的目录结构一样)
`https://base.url/v2/resource/address` => `app/modules/V2/` v2版本的代码

这种方式比较直观，有个问题是命名比较受限

**Comment by NewFuture** [comment]
如果需要更加灵活，可以自定义路由来映射不同请求

* YAF  https://secure.php.net/manual/zh/yaf-router.addconfig.php#refsect1-yaf-router.addconfig-examples
* YYF  https://yyf.newfuture.cc/route/config.html

加上几个规则基本上能满足大部分需求

**Comment by m9rco** [comment]
呃，`modules`下只能为`controller` ,若是再建`app/` 框架意义何在？这样就需要再路由一层？ 灵活是改变路由但的最终`file path`而不是路由规则，最终`file path `只能是约束的三级 我需要的是四级... `Yaf\Route_Interface`规定了啊....

**Comment by NewFuture** [comment]
YAF modules可配置的自由度确实很低,也有一些其他的修改版。

完全自己写当然自由度最高了 😸 , 但你想实现的应该不仅仅是版本的问题
