### ISSUE TITLE
library\Service\Database.php里重写父类\PDO 里的exec()方法如果参数不一致在php5.3+会报致命错误

### ISSUE THREAD

**Issue by idamon** [YunYinORG/YYF#22]
![image](https://user-images.githubusercontent.com/6971821/66255510-c4016280-e7b6-11e9-8bcc-392c8e982545.png)

\PDO父类里的exec()只有一个参数，而以下重写的exec()具有两个参数，在5.3以上的版本里，规定重写方法必须参数一致，否则会报致命错误

![image](https://user-images.githubusercontent.com/6971821/66255516-ded3d700-e7b6-11e9-9fb0-4150ccd6c4d0.png)

**Comment by NewFuture** [comment]
我确认一下

**Comment by NewFuture** [comment]
出现这个是什么版的？

php7  测试都是OK
```php
//不带参数
Db:exec("INSERT INTO test(firstname, lastnamel) VALUES ('John', 'Doe')");
//带参数
Db:exec(
    "INSERT INTO test(firstname, lastnamel) VALUES (?, ?)",
    ["John","Doe"]
);
```

**Comment by idamon** [comment]
抱歉，是我这边调试代码的问题，重写PDO的exec，如果$params形参不设置默认值，确实会报致命错误
```php
 public function exec($sql, array $params = null)
    {
        assert('stripos($sql,"SElECT")!==0', '[Database::exec] select查询语句请使用query方法');
        if ($before = &Database::$before) {
            //执行前调用
            assert('is_callable($before)', '[Database::$before] 应该是可执行的回调');
            call_user_func_array($before, array(&$sql, &$params, 'exec'));
        }
```
另外还有个php断言跟php 7.2.x以上版本的兼容性问题, assert()函数在php7.2.x已经摒弃了字符串参数的写法，会出现警报[https://www.php.net/manual/zh/migration72.deprecated.php]
```php
assert('is_object($obj)') //适用于<php7.2.x
assert(is_object($obj)) //>=7.2.x
```

**Comment by NewFuture** [comment]
断言的问题可以提个PR来fix一下 😄

**Comment by idamon** [comment]
可以
